# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-eb0f59b8-f70c-4ee3-991b-4dc7f4ca0256";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-eb0f59b8-f70c-4ee3-991b-4dc7f4ca0256".device =
    "/dev/disk/by-uuid/eb0f59b8-f70c-4ee3-991b-4dc7f4ca0256";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-eb0f59b8-f70c-4ee3-991b-4dc7f4ca0256";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-eb0f59b8-f70c-4ee3-991b-4dc7f4ca0256";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7540-886C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-502dd682-dcf9-4c70-afb1-1846fb3419ff"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
